### PR TITLE
Bye envy

### PR DESCRIPTION
**Pull request by JackKelly-Bellroy**
The use of the `envy` library is blocking the ability to use GHC 9.2.x: `envy-2.1.0.0` (latest at time of writing) still depends on `bytestring == 0.10.*`, which depends on `base >=4.2 && <4.16` (`base-4.16` and `bytestring-0.11.1.0` ship with GHC 9.2.1.)

`envy` last had a release in 2020-02 and `hal` doesn't really use `envy` for much; IMHO we should remove it and cut an `0.5.0`. This necessitates the removal of several deprecated functions, which we've been threatening since 2021-04-12. That's nearly a year - is that enough warning?

I can get you the EventBridge event PR soon after this one, which will avoid spamming Hackage with too many releases.

### CODE REVIEW

**Comment by IamfromSpace** [comment]
I suppose it's time!  I agree that at this point there's nothing to be gained by waiting any further.

I think I'd like to sneak in #100 for a 0.4.10 before we merge this, I'm just doing the last bit of discovery and validation now.

Also, thoughts on 1.0 instead of 0.5?  Seems like this is a good milestone for it, been stable otherwise, and this knocks out the things I think we all want to see go.

**Comment by JackKelly-Bellroy** [comment]
Yeah, let's get #100 resolved, and the EventBridge mappings can go into a 0.4.10 as well.

**Comment by JackKelly-Bellroy** [comment]
Another thing that might want to happen before 1.0: rearranging the API Gateway modules so we have a sensible place to put HTTP API mappings (which are different to REST API mappings).

**Comment by IamfromSpace** [comment]
Those have definitely been on my list!  Originally I was just thinking that they would be `AWS.Lambda.ApiGateway.HttpRe(quest|response)`.  I suppose it would group more nicely with something like `AWS.Lambda.ApiGateway.Proxy.Request`.  Is that what you were thinking as well?

**Comment by JackKelly-Bellroy** [comment]
Not 100% sure. There appear to be several types of Lambda integration for an API Gateway Request API: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-integration-types.html

* Lambda proxy integration, type `AWS_PROXY`: This is the one we're currently using, where you receive/return JSON versions of the HTTP request/response.
* Lambda custom integration, type `AWS`: This looks like it invokes Lambda the same way as API Gateway can invoke other AWS services, where you can map parts of the request into particular parameters and vice-versa when constructing the response. I think this is so customisable that there's nothing sensible we can provide.

Then, there's the newer HTTP API mappings, which have a different JSON request/response format. These are under the `apigatewayv2` namespace (e.g., AWS CLI uses `aws apigatewayv2 ...` to invoke; `AWS::ApiGatewayV2::*` namespace in CloudFormation). There are already two payload format versions for an API Gateway HTTP API Lambda Proxy Integration, and while API Gateway has some ["smarts"](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) in how it handles responses, an explicit return type would be useful to remove all doubt.

So maybe something like:

```
AWS.Lambda.Events.ApiGateway.ProxyRequest -- API Gateway V1/REST API
AWS.Lambda.Events.ApiGateway.ProxyResponse -- API Gateway V1/REST API
-- To be built by someone someday?
AWS.Lambda.Events.ApiGatewayV2.ProxyRequest.V1 -- API Gateway V2/HTTP API, V1 Payload
AWS.Lambda.Events.ApiGatewayV2.ProxyResponse.V1 -- API Gateway V2/HTTP API, V1 Payload
AWS.Lambda.Events.ApiGatewayV2.ProxyRequest.V2 -- API Gateway V2/HTTP API, V2 Payload
AWS.Lambda.Events.ApiGatewayV2.ProxyResponse.V2 -- API Gateway V2/HTTP API, V2 Payload
```

**Comment by IamfromSpace** [comment]
> I think this is so customisable that there's nothing sensible we can provide.

That was my take as well.  I think the proxy is the much more dominant approach as well.

I think that approach makes sense.  I think in this instance versioning the modules also makes some sense (especially since that mirrors what AWS is doing), because there's little reason not to make both available in the same package--as long as the old ones still theoretically work.

It does seem like the current module is in a reasonable place though, from your suggestion here.  I think we want to do every desirable break now to consolidate them, but also keeping the migration easy certainly has its benefits.

**Comment by JackKelly-Bellroy** [comment]
Is there anything more that needs to happen here? Reading back over the thread, I think we're both happy with the current set of module names.

**Comment by IamfromSpace** [comment]
Agreed!  Apologies, this has been on my mind and just struggling to get that final brainpower to push this over the line.

I’m traveling this week, but just need to get this done.  Early next week I’ll plan to make this happen.

**Comment by JackKelly-Bellroy** [comment]
Hi @IamfromSpace, have you been able to block out some time for this? We're mid-project at the moment so we won't be looking at dependency updates for another few weeks.

**Comment by IamfromSpace** [comment]
Let's do it!  I'm combing though the last of this now just to double-triple-check everything.  Looks great though.

**Review by IamfromSpace — APPROVED** [review]

**Comment by IamfromSpace** [comment]
Planning to do the stackage release on Monday AM (Pacific), just in the odd case that someone has an unguarded version and uses a deprecated function.  @JackKelly-Bellroy, I'll happily do tomorrow if you're looking to get it sooner though; not sure we need that level of caution.  Publish is the easy part :)

**Comment by JackKelly-Bellroy** [comment]
Thank you for this. We don't use stackage snapshots at work, so I'm happy to defer to your best judgement for release timing there.

**Pull request merged**
