### PR TITLE
hal.cabal: Add CHANGELOG.md to extra-source-files

### PR DESCRIPTION
**Pull request by endgame**
This'll make it show up as a change log on future hackage releases.

### CODE REVIEW

**Comment by IamfromSpace** [comment]
Didn't realize this wasn't included before!  The cabal file is currently autogenerated, so we'll need to both add this to the package.yaml and update the cabal file hash.  Been doing this a lot, so I added a patch-1 branch to this repo with a commit on top that does this; you can just pull it in to do so!

**Comment by endgame** [comment]
I think `cabal check` warns about such things, but not sure if it catches this one. Dunno about stack workflows.

**Comment by endgame** [comment]
Running `hpack` doesn't seem to add any more changes to the cabal file, so I think we're good to go.

**Comment by IamfromSpace** [comment]
> Dunno about stack workflows.

Yeah, I'm still not sure the best way to handle this either, I've got an open issue #75.  Without it's a pain for anyone who wants to pull the package from git using cabal, but it's a gotcha with it.  🤷‍♂️ 

Looks good to go here though!

**Review by IamfromSpace — APPROVED** [review]

**Pull request merged**
